### ISSUE TITLE
ユーザーページの実装

### ISSUE THREAD

**Issue by Hanason01** [Hanason01/JamMy.dev#101]
### Tasks
- [ ] マイページと同じ構成で、かつ「フォローする」「フォロー中」ボタンを設置
- [ ] 投稿一覧から当該ページへの遷移が行えるようにする。なお、自分のページへの遷移に関しては、マイページへの遷移とする。
- [ ] 投稿、応募のみを表示させ、privateステータスの投稿が表示しない

### Goals
- [ ] ステータスに応じた、投稿の表示・非表示が正しく行われている
- [ ] マイページで利用したコンポーネントを適切に援用できている
