### ISSUE TITLE
応募機能STEP1-1_録音機能実装（フロント）

### ISSUE THREAD

**Issue by Hanason01** [Hanason01/JamMy.dev#27]
### Tasks
- [ ] Step画面遷移雛形作成
- [ ] 投稿音声のFLAC→AudioBufferへのデコードロジック実装
- [ ] 投稿音声プレビュー機能実装（既存のAudioPlayerコンポーネントを利用）
- [ ] 録音前設定機能（投稿音声を視聴しながら録音）実装
- [ ] 録音前設定機能（カウント、メトロノーム）実装
- [ ] 既存の録音機能に同時再生のオプションを追加実装

### Goal
- [ ] 録音時に投稿音声を聴く設定時に録音ボタンを押して、カウント後に投稿音声が流れる
- [ ] 投稿音声が正しくデコードされる
- [ ] 投稿音声のプレビューが正しく行える
- [ ] 他、援用したコンポーネントが正しく動作する

### 留意点
- [x] Stepperは同時実装するが、STEP1については音声投稿時のものを利用し、propsでフラグを利用し、速度欄の除外、同時再生の有無の追加を行う
- [x] 録音コンポーネントについても、音声投稿時のものにフラグに応じた条件分岐を設置し、フラグによるモードの指定がなければ通常通り投稿音声でも使用できるコンポーネントとして成りたたせる事
