### ISSUE TITLE
ProjectTest(IntegrationTest)

### ISSUE THREAD

**Issue by Hanason01** [Hanason01/JamMy.dev#37]
### Tasks
- [ ] 投稿→応募→合成までの一連のフローのテスト

### Goal
- [ ] ユーザーが新規投稿をし、タイトル、概要、公開範囲、音声を正しく登録できる
- [ ] 他のユーザーが投稿に応募し、応募内容が正しく紐付けされ反映される
- [ ] 投稿者が応募管理機能を使い、音声合成を行い、保存またはプロジェクトを終了できる
