### ISSUE TITLE
フロントの認証ロジックの実装

### ISSUE THREAD

**Issue by Hanason01** [Hanason01/JamMy.dev#55]
### Tasks
- [ ] ログイン認証後のクッキーの管理
- [ ] middleware.jsを用いた静的ページの認証ロジック（未認証ユーザーが認証必須の静的ページへ直接URLを打ってアクセスした場合に認証用の静的ページ→AuthModal表示）
- [ ] リクエストを指定した認証ロジックの実装（認証不可の場合、AuthModalを表示）
- [ ] ログアウト機能の実装

### Goal
- [ ] 静的ページの認証チェックがかかり、ログインモーダルが表示される
- [ ] ログイン後は元のページあるいは未ログインユーザーの場合は投稿一覧ページへリダイレクトされる
- [ ] 認証が必要なリクエストに関わる操作（「応募する」ボタン押下等）をするとそのページでAuthModalが表示される
